version: '3.8'  # Убедитесь, что версия указана

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: weather_test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 89562876
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  web:
    build: .
    command: >
      bash -c "python weather_project/manage.py migrate &&
      python weather_project/manage.py test weather_app &&
      python weather_project/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/marketplace
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: weather_test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 89562876
      DJANGO_SETTINGS_MODULE: weather_project.settings  
      
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python Bot/Bot.py
    environment:
      POSTGRES_DB: weather_test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 89562876
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:

